<style media="screen">
    .filepond--drop-label {
        color: #4c4e53;
        font-size: 12px !important;
    }

    .filepond--label-action {
        text-decoration-color: #babdc0;
    }

    .filepond--panel-root {
        background-color: #edf0f4;
    }

    .filepond--root{
        max-width: 20em;
        margin: 0 auto;
    }

</style>

<div class="content-wrapper">
    <div class="row">

            <div class="col-lg-7">
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>System Settings</h4>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="site-settings-alert"></div>
                        <div class="form-group mb-4 form-float">
                            <div class="form-line">
                                <input type="file" class="filepond" id="site_logo" name="site_logo" accept="image/png, image/jpeg, image/gif"/>
                                <label class="form-label">Logo Setting <strong>(120px X 33px)</strong></label>
                            </div>
                        </div>
                        <form class="site-settings" method="POST">

                            <div class="form-group mb-4 form-float">
                                <div class="form-line">
                                    <label class="form-label">Site Title</label>
                                    <input type="text" id="siteTitle" name="siteTitle" class="form-control" value="<?php echo $sh['config']['siteTitle']; ?>">
                                </div>
                            </div>
                            <div class="form-group mb-4 form-float">
                                <div class="form-line">
                                    <label class="form-label">Site Name</label>
                                    <input type="text" id="siteName" name="siteName" class="form-control" value="<?php echo $sh['config']['siteName']; ?>">
                                </div>
                            </div>
                            <div class="form-group mb-4 form-float">
                                <div class="form-line">
                                    <label class="form-label">Home Page Title</label>
                                    <input type="text" id="homeTitle" name="homeTitle" class="form-control" value="<?php echo $sh['config']['homeTitle']; ?>">
                                </div>
                            </div>
                            <div class="form-group mb-4 form-float">
                                <div class="form-line">
                                    <label class="form-label">Site Keywords</label>
                                    <input type="text" id="siteKeywords" name="siteKeywords" class="form-control" value="<?php echo $sh['config']['siteKeywords']; ?>">
                                </div>
                            </div>
                            <div class="form-group mb-4 form-float">
                                <div class="form-line">
                                    <label class="form-label">Site Description</label>
                                    <textarea name="siteDesc" id="siteDesc" class="form-control" cols="30" rows="5"><?php echo $sh['config']['siteDesc']; ?></textarea>
                                </div>
                            </div>

                            <div class="form-group mb-4 form-float">
                                <div class="form-line">
                                    <label class="form-label">Site Footer</label>
                                    <input type="text" id="site_footer" name="site_footer" class="form-control" value="<?php echo $sh['config']['site_footer']; ?>">
                                </div>
                            </div>


                            <input type="hidden" name="hash_id" value="<?php echo Sh_CreateSession();?>">
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                        </form>
                    </div>
                </div> <!-- card end// -->
            </div>
            <div class="col-lg-5">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4 class="float-start">Voting Settings</h4>
                    </div>
                    <div class="card-body">
                        <div class="form-group mb-4 form-float">
                            <div class="form-line">
                                <button type="button" onclick="resetVotes()" id="vote_resetor" class="btn btn-danger text-white m-t-15 waves-effect">Reset All Votes</button>
                            </div>
                        </div>
                    </div>
                </div> <!-- card end// -->
            </div>

    </div>
</div>



<script>
    let base_url = "<?= $sh['site_url']  ?>";
    let api_path = "/api/xhr_api";
    let new_base_url = base_url+api_path+'/upload_pictures.php';

    FilePond.registerPlugin(
        // encodes the file as base64 data
        FilePondPluginFileEncode,

        // validates files based on input type
        FilePondPluginFileValidateType,

        // corrects mobile image orientation
        FilePondPluginImageExifOrientation,

        // previews the image
        FilePondPluginImagePreview,

        // resizes the image to fit a certain size
        // FilePondPluginImageResize,

        // applies crop and resize information on the client
        FilePondPluginImageTransform,

        FilePondPluginFilePoster,

        FilePondPluginImageEdit

    );

    FilePond.create(
        document.getElementById('site_logo'),{
            labelIdle: `Drag & Drop your picture or <span class="filepond--label-action">Browse</span>`,
            imagePreviewHeight: 100,
            // imageCropAspectRatio: '1:1',
            // imageResizeTargetWidth: 200,
            // imageResizeTargetHeight: 200,
            stylePanelLayout: 'compact circle',
            styleLoadIndicatorPosition: 'center bottom',
            styleButtonRemoveItemPosition: 'center bottom',
            styleButtonEditItemPosition: 'center bottom',
            allowMultiple: false,
            <?php if($sh['config']['site_logo'] != ""): ?>
            files: [
                {
                    // the server file reference
                    source: '<?= $sh['config']['site_logo'] ?>',
                    // set type to local to indicate an already uploaded file
                    options: {
                        type: 'local',
                        file: {
                            name: "<?= $sh['config']['site_logo'] ?>",
                            size: 3001025,
                            type: 'image/jpg',
                        },

                        metadata: {
                            poster: '<?= $sh['config']['site_url']."/".$sh['config']['site_logo'] ?>',
                        },
                    },

                },
            ]
            <?php endif; ?>
        }
    );

    FilePond.setOptions({
        server: {
            timeout: 7000,
            process: {
                url: Sh_Ajax_Requests_File() + '?f=admin_setting&s=update_site_logo',
                method: 'POST',
                withCredentials: false,
                onload: (response) => {
                    var json = (response);
                    var obj = JSON.parse(json);
                    var status = obj.status;
                    if (status == 200) {

                        $("html, body").animate({ scrollTop: 0 }, 150);

                        setTimeout(function () {
                            window.location.href = "<?= $sh['config']['site_url'] ?>/admincpanel/settings";
                        }, 1000);

                        $('.site-settings-alert').addClass('alert alert-success').html('<i class="fa fa-check"></i> Settings updated successfully');

                    }
                },
                onerror: (response) => response.data,
                ondata: (formData) => {
                    formData.append('admin_id', '<?= $sh['admin']['admin_id'] ?>');
                    return formData;
                },
            },
            remove: (source, load, error) => {

                const request = new XMLHttpRequest();
                request.open('DELETE', Sh_Ajax_Requests_File() + '?f=admin_setting&s=remove_logo_image&img=' + source);

                request.onload = function () {
                    if (request.status == 200) {

                        $("html, body").animate({ scrollTop: 0 }, 150);

                        setTimeout(function () {
                            $('.site-settings-alert').removeClass('alert alert-success').empty();
                        }, 2000);

                        $('.site-settings-alert').removeClass('alert alert-danger').addClass('alert alert-success').text("Logo Picture Deleted");

                        load(request.message);
                    } else {

                        $('.site-settings-alert').removeClass('alert alert-success').addClass('alert alert-danger').text("Sorry system could not process your request");

                        error('oh no');
                    }
                };

                request.send();
            }

        }
    });


    /**
     *
     * System Settings
     *
     */

    $(function() {

            // Site Settings
            let form_site_settings = $('form.site-settings');
            form_site_settings.ajaxForm({
                url: Sh_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting',
                beforeSend: function() {
                    form_site_settings.find('button').text('Please wait..').attr("disabled", true);
                },
                success: function(data) {
                    if (data.status == 200) {
                        form_site_settings.find('button').text('Save').attr("disabled", false);
                        $("html, body").animate({ scrollTop: 0 }, "slow");
                        $('.site-settings-alert').addClass('alert alert-success').html('<i class="fa fa-check"></i> Settings updated successfully');
                        setTimeout(function () {
                            $('.site-settings-alert').removeClass('alert alert-success').empty();
                        }, 2000);
                    }
                }
            });

    });

    // delete Page
    function resetVotes(){

        swal({
            title: "Vote about to be reset!",
            text: "Are you sure you want to reset all votes?",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Reset',
            padding: '2em'
        }).then(function(result) {

            if (result.value) {

                $.ajax({
                    url: Sh_Ajax_Requests_File() + '?f=admin_setting&s=reset_all_votes',
                    beforeSend: function() {
                        run_waitMe($('#loader'), 1, 'win8');
                    },
                    success: function(data){

                        $('#loader').waitMe('hide');

                        if(data.status == 200){

                            sureNotify(1,data.message);
                        }else{

                            // Error
                            sureNotify(0,data.message);

                        }

                    }
                });

            }

        });


    }

</script>

