<?php

if (isset($_GET['post_id']) && $_GET['post_id'] > 0){
    // check if Post is existing
    $post_id = Sh_Secure($_GET['post_id']);

    $postExist = getPositionData($post_id);

    if (!$postExist){
        header("Location:" . $sh['config']['site_url'].'/admincpanel/create-position');
        exit();
    }

}else{
    header("Location:" . $sh['config']['site_url'].'/admincpanel/create-position');
    exit();
}

?>
<div class="content-wrapper">
    <div class="row">


        <div class="col-12">
            <div class="content-header">
                <h2 class="content-title">Edit Position</h2>
            </div>
        </div>


        <div class="col-lg-12">
            <div class="card my-4">
                <div class="card-header">
                    <h4 class="float-start">Position Details</h4>
                </div>
                <div class="card-body">

                    <form enctype="multipart/form-data" class="row" data-parsley-validate="data-parsley-validate" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], :disabled, :hidden" id="addUserForm" method="post">

                        <div class="mb-4">
                            <label for="product_name" class="form-label">Position Title</label>
                            <input type="hidden" name="post_id" value="<?= $postExist['post_id'] ?>">
                            <input type="text" placeholder="Position Title" required="required" name="title" value="<?= $postExist['title'] ?>" class="form-control" id="post_title">
                        </div>

                        <div class="mb-4">
                            <label for="product_name" class="form-label">Position Status</label>
                            <select name="status" id="status" class="form-control">
                                <option value="1" <?= ($postExist['status'] == 1) ? 'selected' : '' ?>>Active</option>
                                <option value="0" <?= ($postExist['status'] == 0) ? 'selected' : '' ?>>In-Active</option>
                            </select>
                        </div>

                        <div class="float-end">
                            <button type="submit" id="add_page_btn7" class="btn btn-primary disable_tbn">Update</button>
                        </div>

                    </form>
                </div>
            </div> <!-- card end// -->
        </div>

    </div>
</div>



<script>
    let base_url = "<?= $sh['site_url']  ?>";
    let api_path = "/api/xhr_api";

    /**
     *
     * Add new Page with scripts
     *
     */

    $(function() {


        // create User
        let form_createuser = $('form#addUserForm');
        form_createuser.ajaxForm({
            url: Sh_Ajax_Requests_File() + '?f=admin_setting&s=update_post',
            beforeSend: function() {
                $('#addUserForm').parsley().validate();
                run_waitMe($('#loader'), 1, 'win8');
                form_createuser.find('.disable_tbn').attr('disabled', true);
            },
            success: function(data) {
                // console.log(data);
                $('#loader').waitMe('hide');

                $("html, body").animate({scrollTop: 0}, 150);

                if (data.status == 200) {

                    sureNotify(1, data.message);

                    setTimeout(function () {
                        window.location.href = "/admin-cpanel/create-position";
                    }, 2000);

                } else {

                    sureNotify(0, data.message);
                    form_createuser.find('.disable_tbn').attr('disabled', false);

                }
            }
        });



    });

</script>

