<?php


$allUsersWithNoCond = getallUserAccountData();

$rowCount = count($allUsersWithNoCond);

$baseURL = $sh['config']['site_url'].'f=account&s=account_search';

$limit = 10;

// Initialize pagination class
$pagConfig = array(
    'baseURL' => $baseURL,
    'totalRows' => $rowCount,
    'perPage' => $limit,
    'contentDiv' => 'all-datas',
    'link_func' => 'searchDatasFilter'
);

$pagination =  new AdminPagination($pagConfig);

$allUsers = getallUserAccountData("LIMIT $limit");


?>


<div class="content-wrapper">
    <div class="row">
        
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
            <header class="card-header">
              <h4 class="card-title">Manage Users</h4>
              <p class="card-description"> Manage all Users account here</p>
              <div class="row gx-3">
                  <div class="col-lg-4 col-md-6 me-auto">
                      <input onkeyup="searchDatasFilter();" id="keywords" name="keywords" type="text" placeholder="Search By Name, Matric No" class="form-control">
                  </div>
                  <div class="col-lg-2 col-6 col-md-3">
                      <select onchange="searchDatasFilter()" id="filterByVoteStatus" name="filterByVoteStatus" class="form-select">
                          <option value="" disabled>Status</option>
                          <option value="all">Show All</option>
                          <option value="voted">Voted</option>
                          <option value="not_voted">Not Voted</option>
                      </select>
                  </div>
                  <div class="col-lg-2 col-6 col-md-3">
                      <select onchange="searchDatasFilter()" id="filterByLevel" name="filterByLevel" class="form-select">
                          <option value="all">Show All</option>    
                          <option value="1">100LV</option>
                          <option value="2">200LV</option>
                          <option value="3">300LV</option>
                          <option value="4">400LV</option>
                          <option value="5">500LV</option>
                      </select>
                  </div>
              </div>
          </header>
            <div class="card-body">
                <div class="col-12">
                <div class="table-responsive">

                  <div id="all-datas">
                    <table class="table table-striped table-hover">
                      <thead>
                        <tr>
                          <th scope="col">User</th>
                          <th scope="col">Matric No</th>
                          <th scope="col">Full Name</th>
                          <th scope="col">Level</th>
                          <th scope="col">Vote Status</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php 
                          foreach($allUsers as $aus){
                        ?>
                          <tr>
                            <td class="py-1">
                              <img src="<?= $aus['avatar'] ?>" alt="image"/>
                            </td>
                            <td><?= $aus['username'] ?></td>
                            <td><?= $aus['name'] ?></td>
                            <td><?= $aus['level'] ?></td>
                            <td><?= ($aus['vote_status'] == 1) ? '<p class="badge badge-success">Voted</p>' : '<p class="badge badge-success">Not Yet</p>' ?></td>
                            <td>
                              <a href="">
                                <i class="mdi mdi-settings text-primary"></i>
                              </a>
                              &nbsp; &nbsp;
                              <a href="<?= Sh_Link('admin-cpanel/edit-users?user_id='. $aus['user_id']) ?>">
                                <i class="mdi mdi-grease-pencil text-primary"></i>
                              </a>
                            </td>
                          </tr>
                        <?php } ?>
                        
                      </tbody>
                    </table>
                    <br>
                    <?php echo $pagination->createLinks(); ?>
                  </div>
                    
                  </div>
                </div>
            </div>
            </div>
        </div>
       
    </div>
</div>

<script>
  // search for Accounts
  function searchDatasFilter(page_num) {
        page_num = page_num ? page_num : 0;

        //Mode filtering
        
        let filterByVS = $('#filterByVoteStatus').val();
        let filterByLevel = $('#filterByLevel').val();

        let keywords;

        if($('#keywords').val() != ""){
            keywords = $('#keywords').val();
        }else{
            keywords = "";
        }

        $.ajax({
            type: 'POST',
            url: Sh_Ajax_Requests_File() + '?f=account&s=account_search',
            data:'page='+page_num+'&keywords='+keywords+'&filterByVote='+filterByVS+'&filterByLevel='+filterByLevel,
            beforeSend: function () {
                $("#all-datas").html("<img style='display: flex; width: 30%; height: 30%; justify-content: center; margin: 20px auto;' src='https://i.gifer.com/ZZ5H.gif'>");
            },
            success: function (html) {
                $('#all-datas').html(html);
            }
        });
    } 
</script>