<?php
    $allPosts = getPosts(10000,"`status` = 1 OR `status` = 0");

?>
<div class="content-wrapper">
    <div class="row">


            <div class="col-12">
                <div class="content-header">
                    <h2 class="content-title">Add New Position</h2>
                </div>
            </div>


            <div class="col-lg-5">
                <div class="card my-4">
                    <div class="card-header">
                        <h4 class="float-start">Position Details</h4>
                    </div>
                    <div class="card-body">

                        <form enctype="multipart/form-data" class="row" data-parsley-validate="data-parsley-validate" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], :disabled, :hidden" id="addUserForm" method="post">

                            <div class="mb-4">
                                <label for="product_name" class="form-label">Position Title</label>
                                <input type="text" placeholder="Position Title" required="required" name="title" class="form-control" id="post_title">
                            </div>

<!--                            <div class="mb-4">-->
<!--                                <label for="product_name" class="form-label">Position Faculty</label>-->
<!--                                <input type="text" placeholder="Position Faculty" required="required" name="location" class="form-control" id="location">-->
<!--                            </div>-->

                            <div class="float-end">
                                <button type="submit" id="add_page_btn7" class="btn btn-primary disable_tbn">Publish</button>
                            </div>

                        </form>
                    </div>
                </div> <!-- card end// -->
            </div>
            <div class="col-lg-7">
                <div class="card my-4">
                    <div class="card-header">
                        <h4 class="float-start">Position List</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Position</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach($allPosts as $ps){
                                    ?>
                                    <tr>
                                        <td class="py-1">
                                            <?= $ps['post_id'] ?>
                                        </td>
                                        <td><?= $ps['title'] ?></td>
                                        <td><?= ($ps['status'] == 1) ? '<p class="badge badge-success">Active</p>' : '<p class="badge badge-danger">In-Active</p>' ?></td>
                                        <td>
                                            <a href="javascript:void()" onclick="deletePost(<?= $ps['post_id'] ?>)" id="deletePost">
                                                <i class="mdi mdi-delete text-danger"></i>
                                            </a>
                                            &nbsp; &nbsp;&nbsp; &nbsp;
                                            <a href="<?= Sh_Link('admin-cpanel/edit-position?post_id='. $ps['post_id']) ?>">
                                                <i class="mdi mdi-grease-pencil text-primary"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php } ?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> <!-- card end// -->
            </div>



    </div>
</div>



<script>
    let base_url = "<?= $sh['site_url']  ?>";
    let api_path = "/api/xhr_api";

    //delete positions
    function deletePost(post_id){

        swal({
            title: "Position Deletion!",
            text: "Are you sure you want to delete position?",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Delete',
            padding: '2em'
        }).then(function(result) {

            if (result.value) {

                $.ajax({
                    url: Sh_Ajax_Requests_File() + '?f=admin_setting&s=delete_position&post_id='+post_id,
                    beforeSend: function() {
                        run_waitMe($('#loader'), 1, 'win8');
                    },
                    success: function(data){

                        $('#loader').waitMe('hide');

                        if(data.status == 200){

                            sureNotify(1,data.message);

                            setTimeout(function () {
                                window.location.reload();
                            }, 2000);

                        }else{

                            // Error
                            sureNotify(0,data.message);

                        }

                    }
                });

            }

        });

    }

    /**
     *
     * Add new Page with scripts
     *
     */

    $(function() {


        // create User
        let form_createuser = $('form#addUserForm');
        form_createuser.ajaxForm({
            url: Sh_Ajax_Requests_File() + '?f=admin_setting&s=create_post',
            beforeSend: function() {
                $('#addUserForm').parsley().validate();
                run_waitMe($('#loader'), 1, 'win8');
                form_createuser.find('.disable_tbn').attr('disabled', true);
            },
            success: function(data) {
                // console.log(data);
                $('#loader').waitMe('hide');

                $("html, body").animate({scrollTop: 0}, 150);

                if (data.status == 200) {

                    sureNotify(1, data.message);

                    setTimeout(function () {
                        window.location.reload();
                    }, 2000);

                } else {

                    sureNotify(0, data.message);
                    form_createuser.find('.disable_tbn').attr('disabled', false);

                }
            }
        });



    });

</script>

