<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="Surecoders">
    <meta name="title" content="<?= $sh['title'] ?>">
    <meta name="keywords" content="<?= $sh['keywords'] ?>">
    <meta name="description" content="<?= $sh['description'] ?>">
    <title><?= $sh['title'] ?></title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="<?= $sh['config']['site_url'].'/'.$sh['config']['site_logo'] ?>">

    <link rel="stylesheet" href="<?php echo $sh['config']['theme_assets_url'];?>/css/style.css">

    <?php if (!empty($_SERVER) && !empty($_SERVER['REQUEST_URI'])) {
        $link_text = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
        ?>
        <link rel="canonical" href="<?php echo($link_text) ?>" />
    <?php } ?>


    <script type="text/javascript">
        <?php echo $sh['config']['header_cc']; ?>
        function Sh_Ajax_Requests_File(){
            return "<?php echo $sh['config']['site_url'].'/requests.php';?>"
        }
    </script>

    <script src="<?php echo $sh['config']['theme_assets_url'];?>/plugins/jquery.min.js"></script>
    <script src="<?= Sh_LoadAdminLink('assets/jquery.form.min.js') ?>"></script>

    <link href="<?= Sh_LoadAdminLink('assets/css/waitMe.css') ?>" rel="stylesheet" />
    <script src="<?= Sh_LoadAdminLink('assets/js/waitMe.js') ?>"></script>

    <script src="<?= Sh_LoadAdminLink('assets/js/custom.js') ?>"></script>

    <link href="<?= Sh_LoadAdminLink('plugins/notification/snackbar/snackbar.min.css') ?>" rel="stylesheet" type="text/css" />
    <script src="<?= Sh_LoadAdminLink('plugins/notification/snackbar/snackbar.min.js') ?>"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/parsley.js/2.1.2/parsley.min.js"></script>
    <link href="https://parsleyjs.org/src/parsley.css" rel="stylesheet">
</head>
<body id="loader">
    <div class="main">

        <!-- login page -->
        <?= $sh['content'] ?>
        
    </div>
</body>
</html>