<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="Surecoders">
    <meta name="title" content="<?= $sh['title'] ?>">
    <meta name="keywords" content="<?= $sh['keywords'] ?>">
    <meta name="description" content="<?= $sh['description'] ?>">
    <title><?= $sh['title'] ?></title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="<?= $sh['config']['site_url'].'/'.$sh['config']['partner1_image'] ?>">

    <link rel="stylesheet" href="<?php echo $sh['config']['theme_assets_url'];?>/css/style.css">
</head>
<body>
    <div class="main">

        <!-- login page -->
        <?= $sh['content'] ?>
        
    </div>
</body>
</html>