<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="Surecoders">
    <meta name="title" content="<?= $sh['title'] ?>">
    <meta name="keywords" content="<?= $sh['keywords'] ?>">
    <meta name="description" content="<?= $sh['description'] ?>">
    <title><?= $sh['title'] ?></title>
    
     <!-- Favicon -->
     <link rel="shortcut icon" type="image/x-icon" href="<?= $sh['config']['site_url'].'/'.$sh['config']['partner1_image'] ?>">

    <?php if ($sh['page'] == 'maintenance') { ?>
        <meta name="robots" content="noindex">
        <meta name="googlebot" content="noindex">
    <?php } ?>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="<?php echo $sh['config']['theme_assets_url'];?>/css/style.css">

    <?php if ($sh['page'] == 'page' && !empty($sh['page_d'])) { ?>
        <meta property="og:title" content="<?php echo $sh['page_d']['page_name']; ?>" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="<?php echo Sh_Link($sh['page_d']['page_slug']); ?>" />
        <meta property="og:image" content="<?= Sh_Link('upload/pages/'.$sh['page_d']['pageImg']) ?>" />
        <meta property="og:image:secure_url" content="<?= Sh_Link('upload/pages/'.$sh['page_d']['pageImg']) ?>" />
        <meta property="og:description" content="<?php echo limit_text($sh['page_d']['page_description'], 20); ?>" />
        <meta name="twitter:card" content="summary">
        <meta name="twitter:title" content="<?php echo $sh['page_d']['page_name']; ?>" />
        <meta name="twitter:description" content="<?php echo limit_text($sh['page_d']['page_description'], 20); ?>" />
        <meta name="twitter:image" content="<?= Sh_Link('upload/pages/'.$sh['page_d']['pageImg']) ?>" />
    <?php } ?>

    <?php if ($sh['page'] == 'welcome') { ?>
        <meta property="og:title" content="<?php echo $sh['title'];?>" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="<?php echo $sh['config']['site_url'];?>" />
        <meta property="og:image" content="<?= $sh['config']['site_url'].'/'.$sh['config']['site_logo'] ?>" />
        <meta property="og:image:secure_url" content="<?= $sh['config']['site_url'].'/'.$sh['config']['site_logo'] ?>" />
        <meta property="og:description" content="<?php echo $sh['description'];?>" />
        <meta name="twitter:card" content="summary">
        <meta name="twitter:title" content="<?php echo $sh['title'];?>" />
        <meta name="twitter:description" content="<?php echo $sh['description'];?>" />
        <meta name="twitter:image" content="<?= $sh['config']['site_url'].'/'.$sh['config']['site_logo'] ?>" />
    <?php } ?>

    <?php if (!empty($_SERVER) && !empty($_SERVER['REQUEST_URI'])) {
        $link_text = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
        ?>
        <link rel="canonical" href="<?php echo($link_text) ?>" />
    <?php } ?>


    <script type="text/javascript">
        <?php echo $sh['config']['header_cc']; ?>
        function Sh_Ajax_Requests_File(){
            return "<?php echo $sh['config']['site_url'].'/requests.php';?>"
        }
    </script>

    <script src="<?php echo $sh['config']['theme_assets_url'];?>/plugins/jquery.min.js"></script>
    <script src="<?= Sh_LoadAdminLink('assets/jquery.form.min.js') ?>"></script>


    <link href="<?= Sh_LoadAdminLink('assets/css/waitMe.css') ?>" rel="stylesheet" />
    <script src="<?= Sh_LoadAdminLink('assets/js/waitMe.js') ?>"></script>

    <script src="<?= Sh_LoadAdminLink('assets/js/custom.js') ?>"></script>

    <script src="<?php echo $sh['config']['theme_assets_url'];?>/js/functions.js"></script>

    <link href="<?= Sh_LoadAdminLink('plugins/notification/snackbar/snackbar.min.css') ?>" rel="stylesheet" type="text/css" />
    <script src="<?= Sh_LoadAdminLink('plugins/notification/snackbar/snackbar.min.js') ?>"></script>
</head>
<body>
    <div class="main">
        <!-- Navigation -->
        <div class="nav section">
            <div class="logo">
                <img src="<?= $sh['config']['site_url'] ?>/uploads/others/no-bg-logo.png" alt="">
            </div>
            <input name="" type="checkbox"  id="">
            <div class="humbuger">
                <div class="humb line1"></div>
                <div class="humb line2"></div>
                <div class="humb line3"></div>
            </div>
            <div class="menu">
                <ul>
                    <li>
                        <a href="#" class="active">Home</a>
                    </li>
                    <li>
                        <a href="" class="active">About Us</a>
                    </li>
                    <li>
                        <a href="" class="active">View Candidates</a>
                    </li>
                    <li>
                        <a href="" class="active">Vote</a>
                    </li>
                    <li>
                        <a href="" class="active">
                            Login <i class="fa-solid fa-right-to-bracket"></i> 
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- content -->
        <?= $sh['content'] ?>

        <!-- Footer -->
        <div class="footer section">
            <div class="footer-one">
                <p>Momudu University copyright 2022</p>
            </div>
        </div>
    </div>
</body>
</html>