<?php
session_unset();
if (!empty($_SESSION['admin_id'])) {
    $_SESSION['admin_id'] = '';
    $query = mysqli_query($sqlConnect, "DELETE FROM " .  T_APP_SESSIONS . " WHERE `session_id` = '" . Sh_Secure($_SESSION['admin_id']) . "'");
}
session_destroy();
if (isset($_COOKIE['admin_id'])) {
    $query = mysqli_query($sqlConnect, "DELETE FROM " .  T_APP_SESSIONS . " WHERE `session_id` = '" . Sh_Secure($_COOKIE['admin_id']) . "'");
    $_COOKIE['admin_id'] = '';
    unset($_COOKIE['admin_id']);
    setcookie('admin_id', '', -1);
    setcookie('admin_id', '', -1,'/');
}
$_SESSION = array();
unset($_SESSION);
header("Location: " . $sh['config']['site_url'].'/admincpanel/auth');
exit();