<?php
    // dashboard records
    $dashRecords = dashboardRecords();

    // position data
    $allPosts = getPosts(10000,"`status` = 1 OR `status` = 0");
?>



<div class="content-wrapper">
    
    <div class="row">
        <div class="col-lg-3 grid-margin stretch-card">
            <div class="card">
                <div class="card-body pb-0">
                    <div class="d-flex align-items-center justify-content-between">
                        <h2 class="text-success font-weight-bold"><?= $dashRecords['userCounts'] ?></h2>
                        <i class="mdi mdi-account-outline mdi-18px text-dark"></i>
                    </div>
                </div>
                <canvas id="newClient"></canvas>
                <div class="line-chart-row-title">Users</div>
            </div>
        </div>
        <div class="col-lg-3 grid-margin stretch-card">
            <div class="card">
                <div class="card-body pb-0">
                    <div class="d-flex align-items-center justify-content-between">
                        <h2 class="text-danger font-weight-bold"><?= $dashRecords['candidateCounts'] ?></h2>
                        <i class="mdi mdi-refresh mdi-18px text-dark"></i>
                    </div>
                </div>
                <canvas id="allProducts"></canvas>
                <div class="line-chart-row-title">Candidates</div>
            </div>
        </div>
        <div class="col-lg-3 grid-margin stretch-card">
            <div class="card">
                <div class="card-body pb-0">
                    <div class="d-flex align-items-center justify-content-between">
                        <h2 class="text-info font-weight-bold"><?= $dashRecords['postCounts'] ?></h2>
                        <i class="mdi mdi-file-document-outline mdi-18px text-dark"></i>
                    </div>
                </div>
                <canvas id="invoices"></canvas>
                <div class="line-chart-row-title">Positions</div>
            </div>
        </div>
        <div class="col-lg-3 grid-margin stretch-card">
            <div class="card">
                <div class="card-body pb-0">
                    <div class="d-flex align-items-center justify-content-between">
                        <h2 class="text-warning font-weight-bold"><?= $dashRecords['voteCounts'] ?></h2>
                        <i class="mdi mdi-folder-outline mdi-18px text-dark"></i>
                    </div>
                </div>
                <canvas id="projects"></canvas>
                <div class="line-chart-row-title">Votes</div>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-lg-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Position Break Down</h4>
                    <p class="card-description">
                        All Positions analysis
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Position</th>
                                <th>Candidates</th>
                                <th>Votes</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($allPosts as $ps) {?>
                            <tr>
                                <td><b><?= $ps['title'] ?></b></td>
                                <td><?= getCounterRecords($ps['post_id'], 'candidate', 'post_id') ?></td>
                                <td><?= getCounterRecords($ps['post_id'], 'vote', 'post_id') ?></td>
                                <td><?= ($ps['status'] == 1) ? '<label class="badge badge-success">Active</label>' : '<label class="badge badge-danger">In-Active</label>' ?></td>
                            </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>