<!-- List of Contestants -->
<div class="contest section mg-t">
    <div class="c-rows">
        <div class="cards">
            <div class="card-title">President <label for="">Faculty of Science</label></div>
            
            <div class="all-cards">
                <div class="candidates">
                    <!-- Single card -->
                    <div class="candidate-card">
                        <div class="img">
                            <img src="../images/contenst-1.png" alt="">
                        </div>
                        <div class="desc">
                            <div class="vote-btn">
                                <button class="btn">Vote</button>
                            </div>
                            <div class="v-desc">
                                <h3 class="name">Hassan Tijani.A</h3>
                                <p class="dep">400lv, ZLY</p>
                            </div> 
                        </div>
                    </div>

                    <!-- Single card -->
                    <div class="candidate-card">
                        <div class="img">
                            <img src="../images/contenst-1.png" alt="">
                        </div>
                        <div class="desc">
                            <div class="vote-btn">
                                <button class="btn">Vote</button>
                            </div>
                            <div class="v-desc">
                                <h3 class="name">Hassan Tijani.A</h3>
                                <p class="dep">400lv, ZLY</p>
                            </div> 
                        </div>
                    </div>

                    <!-- Single card -->
                    <div class="candidate-card">
                        <div class="img">
                            <img src="../images/contenst-1.png" alt="">
                        </div>
                        <div class="desc">
                            <div class="vote-btn">
                                <button class="btn">Vote</button>
                            </div>
                            <div class="v-desc">
                                <h3 class="name">Hassan Tijani.A</h3>
                                <p class="dep">400lv, ZLY</p>
                            </div> 
                        </div>
                    </div>
                </div>    
            </div>
            
        </div>

    </div>
</div>