<!-- Hero section --> 
<div class="hero section">
    <div class="left">
        <div class="h-logo">
            <img src="images/no-bg-logo.png" alt="">
        </div>
        <h1 class="h-title">Momudu University</h1>
        <h3 class="h-sub-title">2022 Student Body Election</h3>
        <a href="#" class="btn">Vote Now</a>
    </div>
    <div class="right"></div>
</div>

<!-- List of Contestants -->
<div class="contest section">
    <div class="c-rows">
        <div class="c-title">
            <h3 class="cc-title">Annual Student Body Election is Ongoing</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil nisi repellendus distinctio fugit, dolores facilis modi ab exercitationem excepturi perferendis.</p>
        </div>
        <div class="cards">
            <div class="card-title">President <label for="">Faculty of Science</label></div>
            <div class="all-cards">
                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="images/contenst-1.png" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name">Hassan Tijani.A</h3>
                        <p class="dep">400lv, ZLY</p>
                    </div>
                </div>

                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="images/contenst-1.png" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name">Hassan Tijani.A</h3>
                        <p class="dep">400lv, ZLY</p>
                    </div>
                </div>

                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="images/contenst-1.png" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name">Hassan Tijani.A</h3>
                        <p class="dep">400lv, ZLY</p>
                    </div>
                </div>
            </div>
            
        </div>

        <div class="cards">
            <div class="card-title">President <label for="">Faculty of Science</label></div>
            <div class="all-cards">
                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="images/contenst-1.png" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name">Hassan Tijani.A</h3>
                        <p class="dep">400lv, ZLY</p>
                    </div>
                </div>

                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="images/contenst-1.png" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name">Hassan Tijani.A</h3>
                        <p class="dep">400lv, ZLY</p>
                    </div>
                </div>

                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="images/contenst-1.png" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name">Hassan Tijani.A</h3>
                        <p class="dep">400lv, ZLY</p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>