<style>
    .main .hero{
        background-image: url('<?= $sh['config']['site_url'] ?>/uploads/others/new-bg.jpg');
        background-position: 50% 50%;
        background-size: cover;
        background-repeat: no-repeat;
    }

    .main .hero .right{
       background-image: url('<?= $sh['config']['site_url'] ?>/uploads/others/h-bg.jpg');
       background-repeat: no-repeat;
       background-position: 50% 50%;
       background-size: cover;
   }
</style> 


<!-- Hero section --> 
<div class="hero section">
    <div class="left">
        <div class="h-logo">
            <img src="<?= $sh['config']['site_url'].'/'.$sh['config']['site_logo'] ?>" alt="">
        </div>
        <h1 class="h-title"><?= $sh['config']['siteName'] ?></h1>
        <h3 class="h-sub-title"><?= $sh['config']['siteTitle'] ?></h3>
        <a href="<?= $sh['config']['site_url'].'/vote' ?>" class="btn">Vote Now</a>
    </div>
    <div class="right"></div>
</div>

<!-- List of Contestants -->
<div class="contest section">
    <div class="c-rows">
        <div class="c-title">
            <h3 class="cc-title"><?= $sh['config']['homeTitle'] ?></h3>
            <p><?= $sh['config']['siteDesc'] ?></p>
        </div>


        <?php
            $postsList = getPosts(5);
            foreach($postsList as $PL){
        ?>

        <div class="cards">
            <div class="card-title"><?= $PL['title'] ?><label for=""> <?= $PL['location'] ?></label></div>
            <div class="all-cards">
                <?php 
                    $cands = getCandidates(3, $PL['post_id']);
                    foreach($cands as $cd){
                    $candData = Sh_UserData($cd['user_id']);
                ?>
                <!-- Single card -->
                <div class="card">
                    <div class="img">
                        <img src="<?= $candData['avatar'] ?>" alt="">
                    </div>
                    <div class="desc">
                        <h3 class="name"><?= $candData['name'] ?></h3>
                        <p class="dep"><?= $candData['level'] ?>, ZLY</p>
                    </div>
                </div>
                <?php } ?>
            </div>
            
        </div>

        <?php } ?>
    </div>
</div>