<div class="ps-page--my-account">

    <div class="ps-my-account">
        <div class="container">
            <form class="ps-form--account ps-tab-root mt-0 py-5 g-0" id="login_user" method="post" autocomplete="off">
                <ul class="ps-tab-list">
                    <li class="active"><a href="#">Invalid Password Reset Code</a></li>
                </ul>
                <div class="ps-tabs">
                    <div class="ps-tab active mainlogin" id="sign-in">

                        <div class="valign tag_auth_animation hidden">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 367.805 367.805" xml:space="preserve"> <g> <path style="fill:#3BB54A;" d="M183.903,0.001c101.566,0,183.902,82.336,183.902,183.902s-82.336,183.902-183.902,183.902 S0.001,285.469,0.001,183.903l0,0C-0.288,82.625,81.579,0.29,182.856,0.001C183.205,0,183.554,0,183.903,0.001z"/> <polygon style="fill:#fff;" points="285.78,133.225 155.168,263.837 82.025,191.217 111.805,161.96 155.168,204.801 256.001,103.968"/> </g></svg>
                            <?php echo $sh['lang']['successfully_joined_label'] ?>
                        </div>

                        <div class="ps-form__content">

                            <p class="title"><?php echo $sh['lang']['invalid_markup']; ?></p>
                            <a href="<?php echo Sh_Link('login');?>" class="btn btn-main btn-mat tag_wel_btn">Go back to login</a>
                        </div>
                        <br>
                        <?php if(1>2):?>
                            <?= Sh_LoadPage('login-with/show-icons') ?>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?= Sh_LoadPage('newsletter/content') ?>


