<div class="login-cont">

    <div class="login">
        <div class="left">
            <div class="over-1"></div>
            <div class="over-2"></div>
            <div class="over-3"></div>
            <!-- login image -->

            <h1 class="greet">Welcome To</h1>

            <div class="identity">
                <img src="<?= $sh['config']['site_url'].'/'.$sh['config']['site_logo'] ?>" alt="">
                <h2><?= $sh['config']['siteName'] ?></h2>
            </div>

        </div>
        <div class="right">

            <div class="title">
                <h2>Login.</h2>
            </div>

            <div class="over-4"></div>

            <!-- login form -->
            <form id="login_user" data-parsley-validate="data-parsley-validate" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], :disabled, :hidden" method="POST">

                <div class="errors"></div>
                
                <div id="hs">
                    <div class="form-group">
                        <label for="matric-no">Matric Number</label>
                        <input required type="text" name="username" id="username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input required type="password" name="password" id="password">
                    </div>
                    <div class="form-group">
                        <button class="btn" type="submit">Login</button>
                    </div>
                </div>
                
            </form>
        </div>
    </div>
</div>

<script>
    // LOGIN
    var working = false;
    var $this = $('#login_user');
    var $state = $this.find('.errors');
    var $login_anim = $('#hs');

    $(function() {

        $this.parsley();

        $this.ajaxForm({
            url: Sh_Ajax_Requests_File() + '?f=login',
            beforeSend: function () {
                working = true;
                $this.parsley().validate();
                $this.find('.disable_btn').attr("disabled", true);
                run_waitMe($('#loader'), 1, 'win8');
            },
            success: function (data) {
                if (data.status == 200 || data.status == 600) {
                    $state.removeClass('alert alert-danger').addClass('alert alert-success').html(data.message);
                    $login_anim.hide(500);
                    setTimeout(function () {
                        window.location.href = data.location;
                    }, 1000);
                } else {
                    var errors = data.errors.join("<br>");
                    $state.addClass('alert alert-danger').html(errors);
                    $('#loader').waitMe('hide');
                }
                working = false;
                $this.find('.disable_btn').attr("disabled", false);
            }
        });

    });
</script>

