<div class="login-cont">

    <div class="login">
        <div class="left">
            <div class="over-1"></div>
            <div class="over-2"></div>
            <div class="over-3"></div>
            <!-- login image -->

            <h1 class="greet">Welcome To</h1>

            <div class="identity">
                <img src="../images/no-bg-logo.png" alt="">
                <h2>Momudu University</h2>
            </div>

        </div>
        <div class="right">

            <div class="title">
                <h2>Login.</h2>
            </div>

            <div class="over-4"></div>

            <!-- login form -->
            <form action="#">
                
                <div class="form-group">
                    <label for="matric-no">Matric Number</label>
                    <input type="text" name="" id="matric-no">
                </div>
                <div class="form-group">
                    <label for="matric-no">Password</label>
                    <input type="password" name="" id="matric-no">
                </div>
                <div class="form-group">
                    <button class="btn" type="submit">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    // LOGIN
    var working = false;
    var $this = $('#login_user');
    var $state = $this.find('.errors');
    var $login_anim = $('.tag_auth_animation');

    $(function() {

        $this.ajaxForm({
            url: Sh_Ajax_Requests_File() + '?f=login',
            beforeSend: function () {
                working = true;
                $this.find('.disable_btn').attr("disabled", true);
                run_waitMe($('#loader'), 1, 'win8');
            },
            success: function (data) {
                if (data.status == 200 || data.status == 600) {
                    $login_anim.removeClass('hidden');
                    setTimeout(function () {
                        window.location.href = data.location;
                    }, 1000);
                } else {
                    var errors = data.errors.join("<br>");
                    $state.addClass('alert alert-danger').html(errors);
                    $('#loader').waitMe('hide');
                }
                working = false;
                $this.find('.disable_btn').attr("disabled", false);
            }
        });

    });
</script>

