<div class="ps-page--my-account">

    <div class="ps-my-account">
        <div class="container">
            <form class="ps-form--account ps-tab-root mt-0 py-5 g-0" id="forgot-reset" method="post" data-parsley-validate="data-parsley-validate" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], :disabled, :hidden" autocomplete="off">
                <ul class="ps-tab-list">
                    <li class="active"><a href="#">Password Recovery</a></li>
                </ul>
                <div class="ps-tabs">
                    <div class="ps-tab active mainlogin" id="sign-in">

                        <div class="valign tag_auth_animation hidden">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 367.805 367.805" xml:space="preserve"> <g> <path style="fill:#3BB54A;" d="M183.903,0.001c101.566,0,183.902,82.336,183.902,183.902s-82.336,183.902-183.902,183.902 S0.001,285.469,0.001,183.903l0,0C-0.288,82.625,81.579,0.29,182.856,0.001C183.205,0,183.554,0,183.903,0.001z"/> <polygon style="fill:#fff;" points="285.78,133.225 155.168,263.837 82.025,191.217 111.805,161.96 155.168,204.801 256.001,103.968"/> </g></svg>
                            <?php echo $sh['lang']['email_sent']; ?>
                        </div>


                        <div class="ps-form__content">
                            <h5>Enter new password</h5>

                            <div class="de elHeadlineWrapper" id="tmp_subheadline-10287-108" data-de-type="headline" data-de-editing="false" data-title="sub-headline" data-ce="true" data-trigger="none" data-animate="fade" data-delay="500" data-gramm="false" style="margin-top: 10px; outline: none; cursor: pointer;" aria-disabled="false">
                                <div class="errors"></div>
                                <div class="success"></div>
                            </div>

                            <div class="form-group form-forgot">
                                <input required="" class="form-control" autocomplete="off" autofocus name="password" id="password" type="password" placeholder="Password"><a href="<?= Sh_Link('login') ?>">Remember?</a>
                                <?php if ($sh['config']['password_complexity_system'] == 1) { ?>
                                    <ul class="list-unstyled helper-text elAlign_left" style="color: red;">
                                        <li class="length"><?php echo $sh['lang']['least_characters']; ?></li>
                                        <li class="lowercase"><?php echo $sh['lang']['contain_lowercase']; ?></li>
                                        <li class="uppercase"><?php echo $sh['lang']['contain_uppercase']; ?></li>
                                        <li class="special"><?php echo $sh['lang']['number_special']; ?></li>
                                    </ul>
                                <?php } ?>
                                <input type="hidden" name="id" value="<?php echo $_GET['code'];?>">
                            </div>
                            <div class="form-group submtit">
                                <button type="submit" class="ps-btn disable_btn ps-btn--fullwidth">Recover Password</button>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script>

    $('#forgot-reset').parsley();
    $('#forgot-reset').ajaxForm({
        url: Sh_Ajax_Requests_File() + '?f=reset_password',
        beforeSend: function() {
            $('#forgot-reset').parsley().validate();
            <?php if ($sh['config']['password_complexity_system'] == 1) { ?>
            if ($('.helper-text .length').hasClass('valid') && $('.helper-text .lowercase').hasClass('valid') && $('.helper-text .uppercase').hasClass('valid') && $('.helper-text .special').hasClass('valid')) {
                working = true;
                $('#forgot-reset').find('button').attr("disabled", true);
            }
            else{
                $('#forgot-reset').find('.errors').html("<?php echo($sh['lang']['complexity_requirements']) ?>");
                return false;
            }
            <?php } else{ ?>
            working = true;
            $('#forgot-reset').find('button').attr("disabled", true);
            <?php } ?>
        },
        success: function(data) {
            if (data.status == 200 || data.status == 600) {
                $('.tag_auth_animation').removeClass('hidden');
                setTimeout(function () {
                    window.location.href = data.location;
                }, 1000);
            } else {
                $('#forgot-reset').find('button').attr("disabled", false);
                $('#forgot-reset').find('.errors').html(data.errors);
            }
            working = false;
        }
    });

</script>


<?= Sh_LoadPage('newsletter/content') ?>



