<div class="content-wrapper">
    <div class="row">


            <div class="col-12">
                <div class="content-header">
                    <h2 class="content-title">Create New Admin</h2>
                </div>
            </div>


            <div class="col-lg-12">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4 class="float-start">Admin Details</h4>
                    </div>
                    <div class="card-body">
                        <form enctype="multipart/form-data" class="row" data-parsley-validate="data-parsley-validate" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], :disabled, :hidden" id="addUserForm" method="post">
                            <div class="mb-4">
                                <label for="product_name" class="form-label">Full Name</label>
                                <input type="text" placeholder="Full Name" required="required" name="full_name" class="form-control" id="full_name">
                            </div>

                            <div class="mb-4">
                                <label for="product_name" class="form-label">Username</label>
                                <input type="text" required placeholder="Username" name="username" class="form-control" id="username">
                            </div>

                            <div class="mb-4">
                                <label for="product_name" class="form-label">Password</label>
                                <input type="text" placeholder="Password" required="required" name="password" class="form-control" id="password">
                            </div>

                            <div class="mb-4">
                                <label for="product_name" class="form-label">Phone Number (optional)</label>
                                <input type="text" placeholder="Enter Phone Number" name="phone_number" class="form-control" id="phone_number">
                            </div>

                            <div class="float-end">
                                <button type="submit" id="add_page_btn7" class="btn btn-primary disable_tbn">Publish</button>
                            </div>
                        </form>
                    </div>
                </div> <!-- card end// -->
            </div>

    </div>
</div>



<script>
    let base_url = "<?= $sh['site_url']  ?>";
    let api_path = "/api/xhr_api";

    /**
     *
     * Add new Page with scripts
     *
     */

    $(function() {


        // create User
        let form_createuser = $('form#addUserForm');
        form_createuser.ajaxForm({
            url: Sh_Ajax_Requests_File() + '?f=admin&s=add_new_admin',
            beforeSend: function() {
                $('#addUserForm').parsley().validate();
                run_waitMe($('#loader'), 1, 'win8');
                form_createuser.find('.disable_tbn').attr('disabled', true);
            },
            success: function(data) {
                // console.log(data);
                $('#loader').waitMe('hide');

                $("html, body").animate({scrollTop: 0}, 150);

                if (data.status == 200) {

                    sureNotify(1, data.message);

                    setTimeout(function () {
                        window.location.reload();
                    }, 2000);

                } else {
                    sureNotify(0, data.message);
                    form_createuser.find('.disable_tbn').attr('disabled', false);

                }
            }
        });



    });

</script>

