<?php

if (isset($_GET['user_id']) && $_GET['user_id'] > 0){
    // check if user is existing
    $user_id = Sh_Secure($_GET['user_id']);
    $userExist = Sh_UserExistsByID($user_id);

    if (!$userExist){
        header("Location:" . $sh['config']['site_url'].'/admincpanel/manage-user');
        exit();
    }

}else{
    header("Location:" . $sh['config']['site_url'].'/admincpanel/manage-user');
    exit();
}

$UserData = Sh_UserData($user_id);

?>


<div class="content-wrapper">
    <div class="row">

        <form class="row" data-parsley-validate="data-parsley-validate" data-parsley-excluded="input[type=button], input[type=submit], input[type=reset], input[type=hidden], :disabled, :hidden" id="updateUserForm" method="post">
            <div class="col-12">
                <div class="content-header">
                    <h2 class="content-title">Edit User</h2>
                    <div class="float-end">
                        <button type="submit" id="add_page_btn7" class="btn btn-primary disable_tbn">Update Profile</button>
                    </div>
                </div>
            </div>

        
            <div class="col-lg-7">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4 class="float-start">User Details</h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-4">
                            <label for="product_name" class="form-label">First Name</label>
                            <input type="text" placeholder="First Name" required="required" value="<?= $UserData['first_name'] ?>" name="first_name" class="form-control" id="first_name">
                        </div>

                        <div class="mb-4">
                            <label for="product_name" class="form-label">Last Name</label>
                            <input type="text" placeholder="Last Name" required="required" name="last_name" value="<?= $UserData['last_name'] ?>" class="form-control" id="last_name">
                        </div>

                        <div class="mb-4">
                            <label for="product_name" class="form-label">Middle Name (optional)</label>
                            <input type="text" placeholder="Middle Name" name="middle_name" class="form-control" value="<?= $UserData['middle_name'] ?>" id="middle_name">
                        </div>

                        <div class="mb-4">
                            <label for="product_name" class="form-label">Matric Number</label>
                            <input type="text" placeholder="Matric Number" required="required" name="matric_no" value="<?= $UserData['username'] ?>" class="form-control" id="matric_no">
                        </div>

                        <div class="mb-4">
                            <label for="level" class="form-label">Level</label>
                            <select id="level" name="level" class="form-control">
                                <option <?= ( $UserData['level'] == '1OOLV' ) ? 'selected' : '' ?> value="1">100LV</option>
                                <option <?= ( $UserData['level'] == '200LV' ) ? 'selected' : '' ?> value="2">200LV</option>
                                <option <?= ( $UserData['level'] == '300LV' ) ? 'selected' : '' ?> value="3">300LV</option>
                                <option <?= ( $UserData['level'] == '400LV' ) ? 'selected' : '' ?> value="4">400LV</option>
                                <option <?= ( $UserData['level'] == '500LV' ) ? 'selected' : '' ?> value="5">500LV</option>
                            </select>
                        </div>


                        <div class="mb-4">
                            <label for="phone_number" class="form-label">Phone Number (optional)</label>
                            <input type="text" value="<?= $UserData['phone_number'] ?>" placeholder="Type Phone Number" name="phone_number" class="form-control" id="phone_number">
                        </div>

                        <div class="mb-4">
                            <label for="admin" class="form-label">Admin Access</label>
                            <select id="admin" name="admin" class="form-control">
                                <option <?= ( $UserData['admin'] == '1' ) ? 'selected' : '' ?> value="1">Allow</option>
                                <option <?= ( $UserData['admin'] == '0' ) ? 'selected' : '' ?> value="0">Dis-allow</option>
                            </select>
                        </div>

                        <div class="mb-4">
                            <label for="active" class="form-label">Account Active</label>
                            <select id="active" name="active" class="form-control">
                                <option <?= ( $UserData['active'] == '1' ) ? 'selected' : '' ?> value="1">Enable</option>
                                <option <?= ( $UserData['active'] == '0' ) ? 'selected' : '' ?> value="0">Disable</option>
                            </select>
                        </div>

                        <div class="mb-4">
                            <label for="vote_status" class="form-label">Vote Status</label>
                            <select id="vote_status" name="vote_status" class="form-control">
                                <option <?= ( $UserData['vote_status'] == '1' ) ? 'selected' : '' ?> value="1">Voted</option>
                                <option <?= ( $UserData['vote_status'] == '0' ) ? 'selected' : '' ?> value="0">Not Voted</option>
                            </select>
                        </div>

                    </div>
                </div> <!-- card end// -->
            </div>
            <div class="col-lg-5">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4 class="float-start">User Profile Image</h4>
                    </div>
                    <div class="card-body">
                        <label>Image</label> (One Image is allowed)
                        <div id="mydropzone" class="dropzone dz-clickable"></div>
                        <input type="hidden" name="user_id" id="user_id" value="<?= $UserData['user_id'] ?>">
                        <input type="hidden" value="page_<?= Sh_GenerateKey(4, 10, false, false, true, false) ?>" name="pagecode" id="pagecode" />
                        <br>
                    </div>
                </div> <!-- card end// -->
            </div>

        </form>

    </div>
</div>



<script>
    let base_url = "<?= $sh['site_url']  ?>";
    let api_path = "/api/xhr_api";
    let new_base_url = base_url+api_path+'/upload_pictures.php';

    $(function() {
        $('#add_product').parsley();

        $(".dropzone").disableSelection();
    });

    //Dropzone script for Page images start here
    Dropzone.autoDiscover = false;
    var pro_code_n = jQuery("#pagecode").val();
    var myDropzone = new Dropzone("div#mydropzone", {
        addRemoveLinks: true,
        autoProcessQueue: true,
        parallelUploads: 1,
        maxFilesize: 3, // MB
        acceptedFiles: ".png, .jpeg, .jpg, .gif",
        url: new_base_url,
        renameFile: function(file) {
            return file.name = pro_code_n + '_' + file.name;
        },

    });


    /*Ans code*/
    myDropzone.on("sending", function(file, xhr, formData) {

        formData.append("pagecode", jQuery("#pagecode").val());
        formData.append("user_id", jQuery("#user_id").val());
        formData.append("action", "upload_page_imgs");

    });

    /* Rename Code */

    /* Add Files Script*/
    myDropzone.on("success", function(file, message) {
        $("#msg").html(message);
    });

    myDropzone.on("error", function(data) {
        $("#msg").html('<div class="alert alert-danger">There is some thing wrong, Please try again!</div>');
    });

    myDropzone.on("complete", function(file) {
        //myDropzone.removeFile(file);
    });

    myDropzone.on('removedfile', function (file){
        var pro_code_n = jQuery("#pagecode").val();
        var user_n_id = jQuery("#user_id").val();

        var name = pro_code_n+'_'+file.name;

        $.ajax({
            type: "POST",
            url: new_base_url,
            data: {
                action: "delete_page_imgs",
                fileName: name,
                pro_code: pro_code_n,
                user_id: user_n_id,
                delete_file: 1
            }
        });
    });
    //Dropzone script for property images ends here


    /**
     *
     * Update User data with scripts
     *
     */

    $(function() {


        // create User
        let form_updateuser = $('form#updateUserForm');
        form_updateuser.ajaxForm({
            url: Sh_Ajax_Requests_File() + '?f=account&s=update-user',
            beforeSend: function() {
                $('#updateUserForm').parsley().validate();
                run_waitMe($('#loader'), 1, 'win8');
                form_updateuser.find('.disable_tbn').attr('disabled', true);
            },
            success: function(data) {
                $('#loader').waitMe('hide');

                $("html, body").animate({scrollTop: 0}, 150);

                if (data.status == 200) {

                    sureNotify(1, data.message);

                    setTimeout(function () {
                        window.location.reload();
                    }, 2000);

                } else {

                    sureNotify(0, data.message);
                    form_updateuser.find('.disable_tbn').attr('disabled', false);

                }
            }
        });



    });

</script>

